# Generated by Django 2.2 on 2019-12-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_from_user', verbose_name='image')),
                ('text', models.TextField(max_length=2000, verbose_name='text')),
                ('like', models.IntegerField(default=0, verbose_name='like')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of add')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('image_for_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_for_commit', to='webapp.Image', verbose_name='image for commit')),
            ],
        ),
    ]
